# install themes from https://github.com/alacritty/alacritty-theme?tab=readme-ov-file
# add color to line adding to .bashrc
# export PS1="\[\e[32m\][\[\e[m\]\[\e[31m\]\u\[\e[m\]\[\e[33m\]@\[\e[m\]\[\e[32m\]\h\[\e[m\]:\[\e[36m\]\w\[\e[m\]\[\e[32m\]]\[\e[m\]\[\e[32;47m\]\\$\[\e[m\] "

[general]
import = [
    "~/.config/alacritty/themes/themes/github_dark_colorblind.toml"
]
[font]
normal={family="3270NerdFont"}
size=25

